FROM node:18-alpine

WORKDIR /app

ARG MONGODB_URI=mongodb://default:123456@localhost:27017/turing

ENV MONGODB_URI=${MONGODB_URI}
ENV OPENAI_URL=${OPENAI_URL}
ENV OPENAI_API_KEY=${OPENAI_API_KEY}
ENV OPENAI_URL2=${OPENAI_URL2}
ENV OPENAI_API_KEY2=${OPENAI_API_KEY2}
ENV OPENAI_URL3=${OPENAI_URL3}
ENV OPENAI_API_KEY3=${OPENAI_API_KEY3}
ENV OPENAI_URL4=${OPENAI_URL4}
ENV OPENAI_API_KEY4=${OPENAI_API_KEY4}
ENV OPENAI_URL5=${OPENAI_URL5}
ENV OPENAI_API_KEY5=${OPENAI_API_KEY5}


COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

USER root

CMD ["npm", "start"]